apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticsearchclusters.elasticsearchcluster.prakash.com
spec:
  group: elasticsearchcluster.prakash.com
  names:
    kind: ElasticsearchCluster
    listKind: ElasticsearchClusterList
    plural: elasticsearchclusters
    singular: elasticsearchcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ElasticsearchCluster is the Schema for the elasticsearchclusters
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ElasticsearchClusterSpec defines the desired state of ElasticsearchCluster
          type: object
        status:
          description: ElasticsearchClusterStatus defines the observed state of ElasticsearchCluster
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
